version: "3"
services:
  node-app:
    image: dappled
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - example-net
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
    networks:
      - example-net

networks:
  example-net:
volumes:
  mongo-db:
