version: "3"
services:
  node-app:
    image: dappled
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    depends_on:
      - mongo
    networks:
      - example-net

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
    networks:
      - example-net

  react:
    image: frontend
    build:
      context: ../frontend/testrig-dashboard
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
    depends_on:
      - node-app
    networks:
      - example-net

networks:
  example-net:
volumes:
  mongo-db:
