#frontend block
FROM node as nodework
WORKDIR /frontend/testrig-dashboard
COPY package.json .  
RUN npm install --force
COPY . . 
RUN npm run build


#ngnix block 
FROM nginx:latest
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=nodework /frontend/testrig-dashboard/build .
ENTRYPOINT [ "nginx","-g","daemon off;" ]

